
(require 'ace-jump-mode)
(require 'zen-keybindings)

(add-to-list 'z-evil-normal-keys '("j w" evil-ace-jump-word-mode))
(add-to-list 'z-evil-normal-keys '("j l" evil-ace-jump-line-mode))
(add-to-list 'z-evil-normal-keys '("j c" evil-ace-jump-char-mode))
(add-to-list 'z-evil-visual-keys '("j w" evil-ace-jump-word-mode))
(add-to-list 'z-evil-visual-keys '("j l" evil-ace-jump-line-mode))
(add-to-list 'z-evil-visual-keys '("j c" evil-ace-jump-char-mode))
(add-to-list 'z-emacs-keys '("j w" ace-jump-word-mode))
(add-to-list 'z-emacs-keys '("j l" ace-jump-line-mode))
(add-to-list 'z-emacs-keys '("j c" ace-jump-char-mode))
(add-to-list 'z-emacs-keys '("j w" ace-jump-word-mode))
(add-to-list 'z-emacs-keys '("j l" ace-jump-line-mode))
(add-to-list 'z-emacs-keys '("j c" ace-jump-char-mode))
(add-to-list 'z-global-keys '("w" ace-window))
(add-to-list 'z-global-keys '("s" ace-swap-window))
(add-to-list 'z-global-keys '("d" ace-delete-window))
(provide 'zen-acejump)
